### ISSUE TITLE
install_git

### ISSUE THREAD

**Issue by mattmar** [sparsegdm/sgdm_package#3]
Hi,
devtools::install_git("sparsegdm/sgdm_package") did not work for me but
devtools::install_git**hub**("sparsegdm/sgdm_package") solved the problem however
Cheers

**Comment by sparsegdm** [comment]
Dear matmar, first of all sorry for the lat reply, it seems like Girhub did't inform us about new issues.

Thanks for the comment. We will investigate this issue and update the documentation respectively.
