### ISSUE TITLE
SGDM Dependencies

### ISSUE THREAD

**Issue by Tangaroaluka** [sparsegdm/sgdm_package#4]
Hi all,
I am using ubuntu 16.04 on a linux machine and I had few problems in installing the sgdm package. Particularly install the packages "devtools" due to a problem with the openssl  and "impute", which is a dependency of "PMA" and "sgdm". 

Not sure whether the issues I encountered are also common for window or mac users but I thought to leave the bash script to help linux users . 

Here 
# ' In roder to install sgdm from Github it is necessary to install "devtools".
# ' "devtools" has several problem in installing. Particularly, it requires to install openssl for linux ubuntu.
# ' In adition, Dependencies for sgdm "PMA" requires "impute", which does not install automatically. Follow instruction below.
# ' First install openssl for linux ubuntu

sudo apt-get install libcurl4-openssl-dev libxml2-dev
sudo apt-get install libssl-dev
# 'Second install "devtools"

install.packages("devtools", dependencies=TRUE)
library(devtools)
# '  Third install "impute":Imputation for microarray data.
# '  To install imput follow the code below and visit:
# '  http://www.bioconductor.org/packages/release/bioc/html/impute.html
# '  try http:// if https:// URLs are not supported

source("https://bioconductor.org/biocLite.R")
biocLite("impute")
# '  Fourth install package "PMA"

install.packages("PMA", dependencies=TRUE)
# ' Finaly. install sgdm

install_github("sparsegdm/sgdm_package")
library(sgdm)

Here you go!!!!

**Comment by sparsegdm** [comment]
Dear Tangaroaluka, first of all sorry for the lat reply, it seems like Girhub did't inform us about new issues. 

We weren't aware of this issue since we only tested the package under Windows and OSX. But  great you found a work around. We will incorporate this info in the next release.
